In [5]:
import pandas as pd
import numpy as np

def read_graph(graph_file):
    with open(graph_file,'r') as file:
        lines = file.readlines()
        node_number = int(lines[-1].split()[0]) + 1
        graph = {}
        for i in range(node_number):
            graph.setdefault(int(i),[])
        # print(lines)
        for line in lines:
            load = line.strip("\n").split()
            # print(load)
            a,b,c = int(load[0]),int(load[1]),int(load[2])
            # print(a,b,c)

            graph[a].append([b,c])

    return graph,node_number

graph, node_number = read_graph("./graph_figure6-11.txt")

adj = [graph[i] for i in graph.keys()]
df = pd.DataFrame(np.zeros(shape=(node_number,node_number)),index=[i for i in range(node_number)],columns=[i for i in range(node_number)])
for i in range(node_number):
    for j in adj[i]:
        column = j[0]
        distance = j[1]
        # print(f"{i}번 노드와 {column}번 노드 사이의 거리는 {distance}입니다.")
        df.loc[i,column]=distance
df

      0     1     2     3     4     5     6     7     8     9     10    11
0    0.0  15.0   0.0   0.0  24.0   0.0  11.0   0.0   0.0   0.0   0.0   0.0
1   15.0   0.0  22.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2    0.0  22.0   0.0  18.0  16.0   0.0   0.0   0.0  20.0   0.0   0.0   0.0
3    0.0   0.0  18.0   0.0   0.0  12.0   0.0   0.0   0.0   0.0   0.0   0.0
4   24.0   0.0  16.0   0.0   0.0   0.0  25.0  12.0  24.0   0.0   0.0   0.0
5    0.0   0.0   0.0  12.0   0.0   0.0   0.0   0.0  12.0   0.0   0.0  22.0
6   18.0   0.0   0.0   0.0  25.0   0.0   0.0  15.0   0.0  22.0   0.0   0.0
7    0.0   0.0   0.0   0.0  12.0   0.0  15.0   0.0  30.0   0.0  25.0   0.0
8    0.0   0.0  20.0   0.0  24.0  12.0   0.0  30.0   0.0   0.0  19.0  19.0
9    0.0   0.0   0.0   0.0   0.0   0.0  22.0   0.0   0.0   0.0  19.0   0.0
10   0.0   0.0   0.0   0.0   0.0   0.0   0.0  25.0  19.0  19.0   0.0  21.0
11   0.0   0.0   0.0   0.0   0.0  22.0   0.0   0.0  19.0   0.0  21.0   0.0